export const mockEmployees = [
  {
    id: 1,
    empId: 'EMP-1001',
    name: 'Sarah Jenkins',
    dept: 'Engineering',
    designation: 'Senior Frontend Developer',
    status: 'Active',
    fingerprint: true,
  },
  {
    id: 2,
    empId: 'EMP-1002',
    name: 'Michael Chen',
    dept: 'Engineering',
    designation: 'Backend Lead',
    status: 'Active',
    fingerprint: true,
  },
  {
    id: 3,
    empId: 'EMP-1003',
    name: 'Amara Patel',
    dept: 'Human Resources',
    designation: 'HR Specialist',
    status: 'Active',
    fingerprint: false,
  },
  {
    id: 4,
    empId: 'EMP-1004',
    name: 'David Kim',
    dept: 'Product',
    designation: 'Product Manager',
    status: 'Active',
    fingerprint: true,
  },
  {
    id: 5,
    empId: 'EMP-1005',
    name: 'Elena Rostova',
    dept: 'Design',
    designation: 'UI/UX Designer',
    status: 'Active',
    fingerprint: false,
  },
];

export const mockDepartments = [
  { id: 1, name: 'Engineering' },
  { id: 2, name: 'Human Resources' },
  { id: 3, name: 'Product' },
  { id: 4, name: 'Design' },
];

export const mockAttendanceLogs = [
  {
    id: 101,
    empId: 1,
    name: 'Sarah Jenkins',
    dept: 'Engineering',
    punchIn: '08:55 AM',
    punchOut: null,
    status: 'On Time',
  },
  {
    id: 102,
    empId: 2,
    name: 'Michael Chen',
    dept: 'Engineering',
    punchIn: '09:18 AM',
    punchOut: null,
    status: 'Late',
  },
  {
    id: 103,
    empId: 4,
    name: 'David Kim',
    dept: 'Product',
    punchIn: '08:45 AM',
    punchOut: '05:30 PM',
    status: 'On Time',
  },
];

export const mockHistoryData = [
  {
    id: 1,
    date: '2026-08-18',
    empId: 1,
    empName: 'Sarah Jenkins',
    dept: 'Engineering',
    punchIn: '08:58 AM',
    punchOut: '05:02 PM',
    workingHours: '8h 04m',
    status: 'Present',
  },
  {
    id: 2,
    date: '2026-08-18',
    empId: 2,
    empName: 'Michael Chen',
    dept: 'Engineering',
    punchIn: '09:22 AM',
    punchOut: '05:45 PM',
    workingHours: '8h 23m',
    status: 'Late',
  },
  {
    id: 3,
    date: '2026-08-18',
    empId: 3,
    empName: 'Amara Patel',
    dept: 'Human Resources',
    punchIn: null,
    punchOut: null,
    workingHours: '0h 00m',
    status: 'Absent',
  },
  {
    id: 4,
    date: '2026-08-18',
    empId: 4,
    empName: 'David Kim',
    dept: 'Product',
    punchIn: '08:50 AM',
    punchOut: '05:15 PM',
    workingHours: '8h 25m',
    status: 'Present',
  },
  {
    id: 5,
    date: '2026-08-17',
    empId: 1,
    empName: 'Sarah Jenkins',
    dept: 'Engineering',
    punchIn: '08:50 AM',
    punchOut: '05:10 PM',
    workingHours: '8h 20m',
    status: 'Present',
  },
];